version: '3.3'
services:
    app:
        container_name: fusion-nft_api_${ENV}
        image: fusion-nft-api-${ENV}:1.0.0
        build:
            context: .
            dockerfile: ./Dockerfile
        command: npm run start:${ENV}
        ports:
            - 13337:13337
        environment:
            - DB_HOST=fusion-nft
            - DB_PORT=27017
            - DB_AUTHDATABASE=fusion
        depends_on:
            - fusion-nft-db
        restart: unless-stopped
    fusion-nft-db:
        image: mongo
        container_name: fusion-nft-db
        ports:
            - 27017:27017
        volumes:
            - ./database:/data/db
        restart: always
