export const STONES_0_DUST = 'QmPaZtbvqcXTxzDuU8JeejiLBgGHbuGc1jzQhbEBL5gEKW'
export const STONES_1_MINERAL = 'QmcbWDsr4FgqNaLs6JLgjNEUDguPG8fY8ncbg7wCJHVmD1'
export const STONES_2_CRYSTAL = 'QmawcyCB9ZSPqb8rZ72zojPqBEH3GAHFweTzncohrEYzsY'
export const STONES_3_LIGHTNING =
	'QmUpdNnWzfAtLNSb7BJwLpjxzghnkAiZTQfC9A7mdwEYe9'

export const AMBASSADOR_BASE = 'QmQ6jh77WXJ5LrsMzdgqxVkm7kke45scWoMNvUHH1kFSyJ'
export const AMBASSADOR_JUNIOR_IMAGE_COUNT = 2
export const AMBASSADOR_MASTER_IMAGE_COUNT = 2
export const AMBASSADOR_MAGISTER_IMAGE_COUNT = 2
export const AMBASSADOR_LEGENDARY_IMAGE_COUNT = 2
